---
# tasks file for Lampstack

 
- name: update
  apt:
    update_cache: yes 

- name: Install packages for LAMP stack
  apt:
        name: "{{ item }}"
        state: present
  loop:
        - apache2
        - mysql-server
        - php-fpm
        - php-mysql
  notify: restart services


